### PR TITLE
Update Android image for Circle CI

### PR DESCRIPTION
**Pull request by nymerias**
Use api-28 image for Circle CI
& from https://github.com/intercom/intercom-cordova/pull/269
> Cordova 9 removed support for built-in module
resolution in place of standard approach.

### CODE REVIEW

**Comment by jskrepnek** [comment]
Thanks @nymerias.  Do you have a timeline for when you'll publish a new version to the registry?

**Comment by jskrepnek** [comment]
It's worth noting that this change, from what I can tell, is not backward compatible with earlier versions of the Cordova CLI - so this would represent a major version change of the plugin and configuring the plugin to explicitly require >= 9.

**Comment by nymerias** [comment]
@jskrepnek I don't have a timeline at the moment, and we will need to consider the compatibility as you mentioned. Will this PR resolve the issue you've seen in the interim, since you have a fork of the repo?

**Comment by jskrepnek** [comment]
@nymerias Since the plugin is nested in a subfolder in the repository, we can't actually use it directly until it's published to the registry.  In our fork I've got this same fix, but also the plugin reorganization, so we'll use that until you are able to publish a new version.  It be great as part of the next version if you could reorganize the plugin so that we can add it from a commit/branch/etc rather than the registry.

**Comment by nymerias** [comment]
Thanks for the feedback @jskrepnek we'll take that into consideration as well!

**Comment by nymerias** [comment]
@jskrepnek thanks for your patience, release 7.0.0 with Cordova 9 support is now available: https://github.com/intercom/intercom-cordova/releases/tag/7.0.0

**Pull request merged**
