### PR TITLE
Cordova 9 support

### PR DESCRIPTION
**Pull request by ArnaudSpanneut**
Replace requireCordovaModule to require for non cordova modules

### CODE REVIEW

**Comment by bboyle18** [comment]
Hi @ArnaudSpanneut 👋 
Thanks for this PR.
Unfortunately you seemed to have removed a lot of code from this project, so we can't approve the PR in its current form.
Happy to take a look at again once its tidied up.
If you could also provide a complete list of changes and the reasons for these changes, it would be helpful for us and others reading this PR.

Cheers

Brian

**Comment by jskrepnek** [comment]
The reason there's so much change is because Intercom is nesting the plugin in a sub directory, and due to a bug (?) Cordova plugins cannot be added from a subdirectory.  So anyone that forks this and needs to use the fork while waiting for the PR to merge needs to move the actual plugin files into the root.  That's what the author has done here.

**Comment by jskrepnek** [comment]
https://github.com/intercom/intercom-cordova/pull/269

**Comment by nymerias** [comment]
Thanks @ArnaudSpanneut, this has been addressed and merged here https://github.com/intercom/intercom-cordova/pull/270

**Comment by ArnaudSpanneut** [comment]
Hello 👋
The reason of my changes is because I had first to use the standard node `require` system to get it works.
Then I had troubles to install the package from my repo in my project cause the plugin was in the sub folder. So I did the changes in the same branch.
Thanks for the merge 🙂

**Pull request closed without merging**
