### PR TITLE
Update to cordova-android 8.0.0 and cordova-ios 5.0.0, remove GCM

### PR DESCRIPTION
**Pull request by nymerias**
In this PR I'm 
- updating to cordova-android 8.0.0 and cordova-ios 5.0.0
- removing GCM as [Google has removed GCM](https://developers.google.com/cloud-messaging/faq)
- update Firebase version 
- fixed an issue with push notifications on Android
- updating our Example app to use the newer versions of Cordova
- updating `intercom.gradle` to use the latest version of our Android SDK 

I successfully tested these changes in our Example app on both iOS and Android.

### CODE REVIEW

**Comment by jongbonga** [comment]
I'm getting an issue `ERROR: Could not get unknown property 'cdvCompileSdkVersion' for project ':app' of type org.gradle.api.Project.` on `node_modules/cordova-plugin-intercom/src/android/build-extras-intercom.gradle' line: 54`

using `ionic Capacitor`

**Comment by roxteddy** [comment]
Hello @jongbonga have you found any solution for cdvCompileSdkVersion ? I face the same problem :S

**Comment by jongbonga** [comment]
@roxteddy I migrated to capacitor, so I'm using the capacitor version of the plugin

**Comment by roxteddy** [comment]
@jongbonga ooh I didn't think about this option. Many thanks !

**Pull request merged**
