### PR TITLE
Add separate initialize function to provide appId/apiKey at run time,…

### PR DESCRIPTION
**Pull request by rubenstolk**
… for issue #29

### CODE REVIEW

**Comment by jtreanor** [comment]
Hi @rubenstolk. Sorry for the delay on this.

Thanks for putting this together. As mentioned in #29, this may cause undefined behaviour on Android due to init being called late in the application lifecycle.
We will dive deeper into this before accepting or rejecting the PR.

**Comment by rubenstolk** [comment]
@jtreanor any clues on this one, it would be so awesome if something like this can be done. Even if we could have something where we can configure all the keys for both sandbox and non-sandbox and then have a switch in the JS-library: `intercom.sandbox(true)` would be an option although not as nice :)

**Comment by NickMele** [comment]
@jtreanor completely understand what you mean by making sure that this doesn't cause undesired issues. We have been looking for a way to accomplish this, and before I start to hack a solution together in my project, it would be great to know if you have a timeline for this.

@rubenstolk thanks for making this PR, could be very helpful!

**Comment by jtreanor** [comment]
Closing due to comment in https://github.com/intercom/intercom-cordova/issues/29#issuecomment-206942427

**Pull request closed without merging**
